image: atlassian/default-image:2     

definitions:
      steps:
      - step: &build-and-publish-docker-image
              name: Build docker image
              services:
                - docker #Enable Docker
              script:
              # Set image tag to commit hash
              - export IMAGE_NAME="${DOCKERHUB_USERNAME}/robobot-game-server:latest"
              
              # Build Docker image and push to Dockerhub      
              - docker login -u ${DOCKERHUB_USERNAME} --password ${DOCKERHUB_PASSWORD}
              - docker build -t $IMAGE_NAME .
              - docker push $IMAGE_NAME

      - step: &update-back-end
              name: Pull new game server on back-end
              script:
              - curl -X GET "https://development-robobot.aegisinitiative.io/updateGameServer"

pipelines:       
  branches:
    master:
      - step: *build-and-publish-docker-image
      - step: *update-back-end